<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>EveCommandCenter.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EveCommandCenter.Core\EveCommandCenter.Core.csproj" />
  </ItemGroup>
</Project>
