<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>EveCommandCenter.Presentation</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EveCommandCenter.Application\EveCommandCenter.Application.csproj" />
    <ProjectReference Include="..\EveCommandCenter.Core\EveCommandCenter.Core.csproj" />
    <ProjectReference Include="..\EveCommandCenter.Windows\EveCommandCenter.Windows.csproj" />
  </ItemGroup>
</Project>